support comm usage, and disable consul feature when enable comm

diff --git a/scripts/telegraf-prepare b/scripts/telegraf-prepare
--- a/scripts/telegraf-prepare
+++ b/scripts/telegraf-prepare
@@ -43,6 +43,8 @@ _which() {
 main() {
   for o; do
     case "${o}" in
+      -u)       shift; OPT_ID="$1";      shift;  ;;
+      -i)       shift; OPT_IP="$1";      shift;  ;; 
       -d)       shift; OPT_DC="$1";      shift;  ;;
       -m)       shift; OPT_MARK="$1";    shift;  ;;
       -t)       shift; OPT_TEAM="$1";    shift;  ;;
@@ -57,6 +59,8 @@ main() {
     esac
   done
 
+  OPT_ID="${OPT_ID:-"NULL"}"
+  OPT_IP="${OPT_IP:-"NULL"}"
   OPT_DC="${OPT_DC:-"NULL"}"
   OPT_MARK="${OPT_MARK:-"NULL"}"
   OPT_TEAM="${OPT_TEAM:-"NULL"}"
@@ -64,12 +68,11 @@ main() {
   OPT_TOKEN="${OPT_TOKEN:-"NULL"}"
   OPT_SERVER1="${OPT_SERVER1:-"NULL"}"
   OPT_SERVER2="${OPT_SERVER2:-"NULL"}"
-  OPT_SCHEME="${OPT_SCHEME:="http"}"
+  OPT_SCHEME="${OPT_SCHEME:-"http"}"
 
-  if [[ $OPT_DC == "NULL" \
-        && $OPT_MARK == "NULL" \
-        && $OPT_TEAM == "NULL" ]]; then
-    error "both of the -d, -m, -t are NULL, skip..."
+  if [[ ($OPT_ID == "NULL" && $OPT_IP == "NULL") && \
+        ($OPT_DC == "NULL" && $OPT_MARK == "NULL" && $OPT_TEAM == "NULL") ]]; then
+    error "both of the -u -i or -d, -m, -t are NULL, skip..."
   fi
 
   if [[ $OPT_SERVER1 == "NULL" \
@@ -82,30 +85,64 @@ main() {
     error "schema must be http or https"
   fi
 
-  IP=$(get_one_ip $OPT_NET)
-  IP="${IP:-"NULL"}"
+  if [[ ! $(is_ip_private $OPT_SERVER1) || ! $(is_ip_private $OPT_SERVER2) ]]; then
+    OPT_SCHEME="https"
+  fi
 
   if grep '{{graphites}}' /etc/telegraf/telegraf.conf >/dev/null 2>&1; then
-    SERVERS=$(get_graphite_servers $OPT_TEAM $OPT_MARK $OPT_TOKEN $OPT_SERVER1 $OPT_SERVER2 $OPT_SCHEME)
+    SERVERS=$(get_graphite_servers $OPT_ID $OPT_TEAM $OPT_MARK $OPT_TOKEN $OPT_SERVER1 $OPT_SERVER2 $OPT_SCHEME)
     if [ "$SERVERS" ]; then
-      sed -i "s/{{graphites}}/$SERVERS/" /etc/telegraf/telegraf.conf
-      [[ "$?" -eq 0 ]] && {
-        log "change servers to $SERVERS ok"
-      } || {
-        error "change servers to $SERVERS error"
-      }
+      if grep '{{graphites}}' /etc/telegraf/telegraf.conf >/dev/null; then
+        sed -i "s/{{graphites}}/$SERVERS/" /etc/telegraf/telegraf.conf
+        [[ "$?" -eq 0 ]] && {
+          log "change servers to $SERVERS ok"
+        } || {
+          error "change servers to $SERVERS error"
+        }
+      fi
 
       if [[ $OPT_SCHEME == "https" ]]; then
-        sed -i "s/#tls/tls/g" /etc/telegraf/telegraf.conf
-        sed -i "s/#insecure_skip_verify/insecure_skip_verify/" /etc/telegraf/telegraf.conf
+        if grep '#tls' /etc/telegraf/telegraf.conf >/dev/null; then
+          sed -i "s/#tls/tls/g" /etc/telegraf/telegraf.conf
+          sed -i "s/#insecure_skip_verify/insecure_skip_verify/" /etc/telegraf/telegraf.conf
+	fi
       fi
     else
       error "no consul server alive!"
     fi
   fi
 
-  # at least one server ok, then change the telegraf default
+  if [[ "$OPT_ID" != "NULL" && "$OPT_IP" != "NULL" ]]; then
+    # delete team, mark, dc line
+    if grep '$MARK' /etc/telegraf/telegraf.conf >/dev/null; then
+      sed -i "5,7d" /etc/telegraf/telegraf.conf
+    fi
+    
+    # at least one server ok, then change the telegraf default
   cat <<EOF > /etc/default/telegraf
+ID="$OPT_ID"
+IP="$OPT_IP"
+EOF
+
+  if [[ $OPT_TOKEN != "NULL" ]]; then
+cat <<EOF >> /etc/default/telegraf
+SCHEME="$OPT_SCHEME"
+TOKEN="$OPT_TOKEN"
+SERVER="$OPT_SERVER1, $OPT_SERVER2"
+EOF
+  fi
+
+  else
+    # delete id line
+    if grep '$ID' /etc/telegraf/telegraf.conf >/dev/null; then
+      sed -i "4d" /etc/telegraf/telegraf.conf
+    fi
+
+    IP=$(get_one_ip $OPT_NET)
+    IP="${IP:-"NULL"}"
+
+    # at least one server ok, then change the telegraf default
+    cat <<EOF > /etc/default/telegraf
 DC="$OPT_DC"
 MARK="$OPT_MARK"
 TEAM="$OPT_TEAM"
@@ -114,6 +151,7 @@ TOKEN="$OPT_TOKEN"
 SERVER="$OPT_SERVER1, $OPT_SERVER2"
 SCHEME="$OPT_SCHEME"
 EOF
+  fi
 
   if [[ "$?" -eq 0 ]]; then
     log "change global tags ok"
@@ -121,34 +159,100 @@ EOF
     error "change global tags error"
   fi
 
+  cat <<BANNER
+----------------------------------------------------------------------
+Thanks for using telegraf!
+
+  /etc/telegraf/telegraf.conf
+  /etc/telegraf/telegraf.d
+  systemctl start telegraf
+
+----------------------------------------------------------------------
+BANNER
+
 }
 
+is_ip_private() {
+  local ip="$1"
+  echo -e "$ip" | \
+    perl -ne '
+      BEGIN {
+        sub ip_int {
+          my $ip = shift;
+          return 0 unless defined $ip;
+          my $ipint = 0;
+          my $i = 3;
+          foreach ( $ip =~ /\d+/g) {
+            $ipint += ($_ << (8*$i--));
+          }
+         
+          return $ipint;
+        }
+    
+        # internal ip range
+        sub is_in_private {
+	  my $ip = shift;
+	  return 0 if length($ip) < 7;
+	  $ip =~ s/:\d+$//g;
+          my $ipint = ip_int($ip);
+         
+          if (($ipint >= 167772160 && $ipint <= 184549375)
+             || ($ipint >= 2886729728 && $ipint <= 2887778303)
+             || ($ipint >= 3232235520 && $ipint <= 3232301055)) {
+            return 1;
+          }
+          else {
+            return 0;
+          }
+        }
+      };
 
+      chomp;
+      my $ip = $_;
+      if (is_in_private($ip)) {
+        exit 0;
+      }
+
+      exit 1;
+    '
+}
 
 get_graphite_servers() {
-  local team="$1"
-  local mark="$2"
-  local token="$3"
-  local server1="$4"
-  local server2="$5"
-  local scheme="$6"
+  local id="$1"
+  local team="$2"
+  local mark="$3"
+  local token="$4"
+  local server1="$5"
+  local server2="$6"
+  local scheme="$7"
   local key="telegraf/${team}/${mark}/graphite_server"
 
-  local value=""
-  for server in $server1 $server2; do
-    if [[ $scheme == "http" ]]; then
-      value=$(consul-kv -server $server -token $token -key $key)
-    else
-      key="telegraf/${team}/${mark}/graphite_server_https"
-      value=$(consul-kv -tls -server $server -token $token -key $key)
-    fi
+  if [[ $id != "NULL" ]]; then
+    key="telegraf/comm/graphite_server"
+  fi
 
-    if [ "$?" -ne 0 ]; then
-      value=""
-    else
-      break
-    fi
-  done
+  local value=""
+  if [[  $token != "NULL" ]]; then
+    for server in $server1 $server2; do
+      if [[ $scheme == "http" ]]; then
+        value=$(consul-kv -server $server -token $token -key $key)
+      else
+        key="telegraf/${team}/${mark}/graphite_server_https"
+        if [[ $id != "NULL" ]]; then
+          key="telegraf/comm/graphite_server_https"
+        fi
+        value=$(consul-kv -tls -server $server -token $token -key $key)
+      fi
+    
+      if [ "$?" -ne 0 ]; then
+        value=""
+      else
+        break
+      fi
+    done
+  else
+    value="$server1, $server2"
+  fi
 
   verify_servers "$value"
 }
@@ -289,6 +393,8 @@ telegraf-prepare - set the global tags and graphite servers for the telegraf set
 
   Usage: telegraf-tags [OPTIONS]
   OPTION:
+    -u set the ID tag, default is NULL.
+    -i set the IP tag, used with -u, default is NULL.
     -d set the DC tag, default is NULL.
     -m set the MARK tag, default is NULL.
     -t set the TEAM tag, default is NULL.
